### ISSUE TITLE
Rejected promise during reconnection

### ISSUE THREAD

**Issue by baczus** [davinkevin/AngularStompDK#42] opened 2016-06-28 23:08 UTC
Hi,
I noticed that library rejects promise when connection fails and creates new one after dealy (_this.settings.timeOut_). If I set 30 seconds to reconnect, during this time functions _send_ and _unsubscribe_ won't work properly, because they rely on promise, which is rejected.

**Comment by davinkevin** [comment] 2016-06-29 03:58
You want to send data when the system isn't connected ? Even if the modification are made to support that, the Stomp.js underlying system wont allow this operation. 

From the official doc of [Stomp.js](http://jmesnil.net/stomp-websocket/doc/) : 

> When a client is disconnected, it can no longer send or receive messages

So, I think the problem is somewhere else. You have to choose a smaller timeOut or check the state of the connection. I could add a method on the service to say if the system is connected or not (which will rely on the state of the promise).

**Comment by baczus** [comment] 2016-06-29 06:43
Good point. Right now it is imposibble to determine state of the connection. It would be great if you could add such a method.

**Comment by davinkevin** [comment] 2016-06-29 09:40
I'll close this issue and open another to add this element :D

**Closed by davinkevin** 2016-06-29 09:40 UTC
